baseURL = 'https://gregueria.icu/'
title = 'å†æœƒï¼Œè¬è¬æ‰€æœ‰çš„é­š'
theme = 'newspaper'
languageCode = "zh-cn"
hasCJKLanguage = true

[module]
[module.hugoVersion]
extended = true
min      = "0.41.0"

[markup]
[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos      = false
codeFences         = true
guessSyntax        = false
hl_Lines           = ''
hl_inline          = false
lineAnchors        = ''
lineNoStart        = 1
lineNos            = false
lineNumbersInTable = true
noClasses          = true
noHl               = false
style              = 'rrt'
tabWidth           = 4

[markup.tableOfContents]
startLevel = 2
endLevel   = 3
ordered    = false

[params]
sidebar_icon = "/cat/checkeredblank.gif"

[params.theme_config]
appearance        = "auto"
back_home_text    = "Back"
date_format       = "2006-01-02"
isListGroupByDate = true
isShowFooter      = true

[[params.sidebar_menu]]
icon = "/cat/cat89.gif"
name = "Music!"
content = "<a href=\"https://photo.gregueria.icu//\" target=\"_blank\">The Cat Lady OST ğŸµ</a>"

[[params.sidebar_menu]]
icon = "/cat/240f9f9b.gif"
name = "Book"
content = "<p>å‘¢æ’å†‡å’©å¥½ç‡å–!</p>"

[[params.sidebar_menu]]
icon = "/cat/camera4.gif"
name = "Photos"
content = "<a href=\"https://open.spotify.com/playlist/1b4FV7h1ROLP0Wk6bmk7xo?si=C76ZwDu3Tp267dZfE-E6Tg/\" target=\"_blank\">Darkness in my Eyes</a><span> ğŸ“·ï¼ˆå¥è¿™æ ·å·®ç”Ÿæ–‡å…·å¤šï¼‰</span>"

[params.meowBox]
enabled = true
images = [
    "https://pub-219f59729cc7474d97beb0f99a13e6bd.r2.dev/picture/2024/12/e5b786e27835fd295754ce15d32f9654.jpg",
    "https://pub-219f59729cc7474d97beb0f99a13e6bd.r2.dev/2025/008oVlcxgy1hz9pc597lbj32c0340b29.jpg",
    "https://img.gregueria.icu/2025/008oVlcxgy1htrm5kk1vyj32c0340npd.jpg",
    "https://pub-219f59729cc7474d97beb0f99a13e6bd.r2.dev/2025/008oVlcxgy1hzarjm6thtj32c03401kz.jpg"
]






[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Archive"
url = "/posts"
weight = 2

[[menu.main]]
name = "Friends"
url = "/links"
weight = 3

[[menu.main]]
name = "Museum"
url = "/collection"
weight = 4

# [[menu.main]]
# name = "RSS"
# url = "/index.xml"
# weight = 4

[outputs]
home = ["HTML"]

